# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- task: FuncToolsInstaller@0
  inputs:
    version: 'latest'

- task: AzureFunctionApp@2
  inputs:
    connectedServiceNameARM: 'Azure for Students(12c692a0-00e1-447a-8d87-2712018a0472)'
    appType: 'functionAppLinux'
    appName: 'valera'
    package: '$(System.DefaultWorkingDirectory)/alerts'
    runtimeStack: 'PYTHON|3.10'
  