# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: AzureAppServiceSettings@1
  inputs:
    azureSubscription: 'Azure for Students(12c692a0-00e1-447a-8d87-2712018a0472)'
    appName: 'valera'
    resourceGroupName: 'valera_group'
    appSettings: |
      [
        {
          "name": "DISCORD_WEBHOOK_URL",
          "value": "https://discord.com/api/webhooks/1237706864897032193/HAAUgkvxcdTeLtAnYmCQd9QMjZdwv4y7lodkAdEYohTDrD0O6g_noI0zhKlWZNQIuH6H"
        },
        {
          "name": "fileblob123_STORAGE",
          "value": "DefaultEndpointsProtocol=https;AccountName=fileblob123;AccountKey=N5AguRiqUwPmU97UIiCrbDAhYHhl1FOsXf7RqifV7QCnUyxYQkkbyiQ29tv4bC4gRKdfnjLqp0iw+AStwiLcQQ==;EndpointSuffix=core.windows.net"
        }
      ]

- task: AzureFunctionApp@2
  inputs:
    connectedServiceNameARM: 'Azure for Students(12c692a0-00e1-447a-8d87-2712018a0472)'
    appType: 'functionAppLinux'
    appName: 'valera'
    package: '$(System.DefaultWorkingDirectory)/alerts'
    runtimeStack: 'PYTHON|3.10'
  